openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: API documentation for the Contacts application. Manage user contacts and authentication, including endpoints for creating, retrieving, updating, and deleting contacts.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Contacts
    description: "Manage user contacts: create, retrieve, update, and delete."
  - name: Auth
    description: Authentication and token management endpoints.
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw-mongodb-n160.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth//login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth//refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth//logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth//send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email/post.yaml
  /auth//reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd/post.yaml
  /auth//get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/get-oauth-url/get.yaml
  /auth//confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
